name: Call workflow dispatch
on:
  push:

env:
  MY_SECRET: 'NOT_A_SECRET'

jobs:
  set-env:

  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/work1.yml
    with:
      config-path: .github/labeler.yml
      version: ${{MY_SECRET}}
  say_hello:
    runs-on: ubuntu-latest
    name: do something
    env:
      WEBHOOK_TOKEN: ${{ github.event.inputs.WEBHOOK_TOKEN }}
    environment: ${{ github.event.inputs.DEPLOY_TO }}
    steps:
      - name: Echo
        run: |
          echo "$WEBHOOK_TOKEN"