name: Call workflow dispatch
on:
  push:

env:
  MY_SECRET: 'NOT_A_SECRET'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.save_output.outputs.test_var }}
    steps:
    - id: save_output
      run: echo "test_var=$MY_SECRET" >> $GITHUB_OUTPUT
  test-output:
    runs-on: ubuntu-latest
    needs: [ set-env ]
    steps:
      - name: echo output
        run: echo ${{ needs.set-env.outputs.output1 }}

  call-workflow-2-in-local-repo:
    needs: [set-env]
    steps:
      - name: Set Env Var
        run: |
          export VERSION=TACO_BELL
          echo "NABOO_VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: echo output
        run: echo ${{ needs.set-env.outputs.output1 }}
      - name: Run Tests
        uses: ./.github/workflows/work1.yml
        secrets: inherit
        with:
          config-path:  ${{ env.NABOO_VERSION }}
          version: ${{needs.set-env.outputs.output1}}
  say_hello:
    runs-on: ubuntu-latest
    name: do something
    env:
      WEBHOOK_TOKEN: ${{ github.event.inputs.WEBHOOK_TOKEN }}
    environment: ${{ github.event.inputs.DEPLOY_TO }}
    steps:
      - name: Echo
        run: |
          echo "$WEBHOOK_TOKEN"